# Generated by Django 5.1.2 on 2024-10-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'outlet',
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'parameter_type',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('preview', models.CharField(blank=True, max_length=255, null=True)),
                ('url_address', models.CharField(max_length=80)),
                ('connection_login', models.CharField(max_length=50)),
                ('connection_password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('roi_polygons_points', models.JSONField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.outlet')),
            ],
            options={
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='CameraParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.camera')),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.parametertype')),
            ],
            options={
                'db_table': 'camera_parameter',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField()),
                ('record_video', models.CharField(blank=True, max_length=255, null=True)),
                ('record_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.camera')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
