# Generated by Django 5.1.2 on 2025-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='frame',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
