# Generated by Django 5.1.2 on 2025-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_record_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='frame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
